gui:
  sidePanelWidth: 0.2 # gives you more space to show things side-by-side
  scrollHeight: 10 # how many lines you scroll by

git:
  paging:
    colorArg: never
    pager: ydiff -p cat -s  --width={{columnWidth}}

customCommands:
  - key: "C"
    command: "ccgit"
    context: "files"
    subprocess: true
    description: "Create new conventional commit"
    stream: true
    loadingText: "Creating conventional commit..."
